### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by abdulmalikkhan655** [sfllhkhan95/paint#4]
Hello ,@sfllhkhan95  I want contribute to paint r so i designed a new logo for paint and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my designed

**Comment by sfllhkhan95** [comment]
Sure. I'd like to see what you've designed

**Comment by abdulmalikkhan655** [comment]
sir this is my logo preview please select your logo as soon as  i am
waiting for your reply

**Comment by abdulmalikkhan655** [comment]
hello @sfllhkhan95  sir any updates ??

**Comment by sfllhkhan95** [comment]
Hi @abdulmalikkhan655. The logos you shared are good but not exactly what I want for this app. I'm happy with our current logo for the time being.
